//
//  ManaFont.swift
//  magic-hat
//
//  Mana symbols as text from the bundled Mana font (SIL OFL,
//  Resources/MANA-LICENSE.txt) — the same approach as Keyrune for set
//  symbols: deterministic, offline, tintable, drawn by the text pipeline.
//  `mana-map.json` maps a glyph name (Mana's CSS class minus `ms-`) to its
//  code point and is generated by scripts/make-mana-map.py.
//
//  Only *single* glyphs are in the map. Hybrid symbols ({W/U}, {2/W},
//  {W/P}) are composed by ManaSymbolView from two single glyphs over a split
//  background, exactly as Mana's own CSS does it.
//

import Foundation
import CoreText
import UIKit

nonisolated enum ManaFont {
    /// PostScript name of the registered font, or nil if registration failed.
    nonisolated(unsafe) private(set) static var fontName: String? = nil

    /// Glyph name -> single-character string.
    static let glyphs: [String: String] = {
        guard let url = Bundle.main.url(forResource: "mana-map", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let raw = try? JSONDecoder().decode([String: String].self, from: data)
        else { return [:] }
        var out: [String: String] = [:]
        out.reserveCapacity(raw.count)
        for (name, hex) in raw {
            if let value = UInt32(hex, radix: 16), let scalar = Unicode.Scalar(value) {
                out[name] = String(Character(scalar))
            }
        }
        return out
    }()

    private static let registration: Bool = {
        guard let url = Bundle.main.url(forResource: "mana", withExtension: "ttf") else { return false }
        var error: Unmanaged<CFError>?
        let ok = CTFontManagerRegisterFontsForURL(url as CFURL, .process, &error)
        let alreadyRegistered = (error?.takeRetainedValue() as Error?).map {
            ($0 as NSError).code == CTFontManagerError.alreadyRegistered.rawValue
        } ?? false
        guard ok || alreadyRegistered else { return false }

        if let descriptors = CTFontManagerCreateFontDescriptorsFromURL(url as CFURL) as? [CTFontDescriptor],
           let first = descriptors.first,
           let name = CTFontDescriptorCopyAttribute(first, kCTFontNameAttribute) as? String {
            fontName = name
            return true
        }
        return false
    }()

    /// Registers the font once. Safe to call repeatedly.
    @discardableResult
    static func register() -> Bool { registration }

    /// Glyph by Mana name ("w", "tap", "creature", "ability-flying").
    static func glyph(named name: String) -> String? {
        guard register() else { return nil }
        return glyphs[name]
    }

    /// Glyph for one part of a Scryfall mana symbol: "W", "2", "T", "∞".
    static func glyph(forPart part: String) -> String? {
        glyph(named: glyphName(forPart: part))
    }

    /// Scryfall symbol part -> Mana glyph name. Numbers map to themselves.
    static func glyphName(forPart part: String) -> String {
        switch part.uppercased() {
        case "T": return "tap"
        case "Q": return "untap"
        case "E": return "e"
        case "S": return "s"
        case "P": return "p"
        case "C": return "c"
        case "∞": return "infinity"
        case "½": return "1-2"
        case "CHAOS": return "chaos"
        case "A": return "acorn"
        case "TK": return "tk"
        case "PW": return "planeswalker"
        case "HW": return "w"      // half-white: Unhinged only; draw W
        case "HR": return "r"
        case "D": return "d"       // land drop (Unfinity)
        case "L": return "l"       // legendary (Unfinity)
        default: return part.lowercased()
        }
    }
}
